### ISSUE TITLE
css

### ISSUE THREAD

**Issue by mglknFSD** [Euyevnc/Ui-kit-and-SitePages#41]
Все медиа запросы пишем внутри селекторов. [bp](https://github.com/fullstack-development/front-end-best-practices/blob/master/CSS/README.md#2.13)

![media](https://user-images.githubusercontent.com/75975369/132123296-e88b0309-d644-48d7-9089-e1ae24c0ec82.jpg)

**Comment by mglknFSD** [comment]
Вот для таких вещей лучше использовать переменную блока

![radios](https://user-images.githubusercontent.com/75975369/132123892-9bcd32ab-93d3-44fe-a5c2-1b952872d7a0.jpg)

Например.

```css

.some {
  $block: &;

  &__element-1 {
    &:focus + #{$block}__element-2 {
      ...
    }
  }
}

```
